name: Post Daily Tweet

on:
  workflow_dispatch: # Allows you to run it manually from the Actions tab
  schedule:
    # Runs at 14:00 and 22:00 UTC, which is 9 AM and 5 PM CDT
    # You can change these times. Use a Crontab generator for help.
    - cron: '0 14,22 * * *'

jobs:
  build-and-post:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tweepy google-api-python-client google-generativeai

      - name: Run the Tweet Bot
        env:
          # This makes the secrets available to the Python script
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          TWITTER_API_KEY: ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_SECRET: ${{ secrets.TWITTER_API_SECRET }}
          TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: python Autotweet.py
